export const GET_TAX_DATA_REQUEST = "GET_TAX_DATA_REQUEST";
export const GET_TAX_DATA_SUCCESS = "GET_TAX_DATA_SUCCESS";
export const GET_TAX_DATA_FAILURE = "GET_TAX_DATA_FAILURE";

export const POST_TAX_DATA_REQUEST = "POST_TAX_DATA_REQUEST";
export const POST_TAX_DATA_SUCCESS = "POST_TAX_DATA_SUCCESS";
export const POST_TAX_DATA_FAILURE = "POST_TAX_DATA_FAILURE";
